### ISSUE TITLE
Build structural elements

### ISSUE THREAD

**Issue by ronniefcodes** [ronniefcodes/portfolio-react#1]
## Description

This task will cover creating all base template components required for the portfolio site.

## Tasks

The following components (and relevant subcomponents) must be created:

- [x] Header element
  - [x] Page 'title' (for name) and subtitle elements
  - [x] Contact information (for email, phone number, etc.)
- [x] Main page carousel
  - [x] Navigation elements (left/right arrows)
  - [x] Splash images
