### ISSUE TITLE
Create app structure to support dynamic data

### ISSUE THREAD

**Issue by ronniefcodes** [ronniefcodes/portfolio-react#2]
## Description

This will include the creation of any functional required to support the app reading provided config data in order to dynamically populate page fields.

## Tasks

- [x] Update the following components to expect content provided as a prop value:
  - [x] Header (title, subtitle)
  - [x] ContactInformation (array with nam, href, aria-labels, etc.)
  - [x] Main Carousel (dynamic splash image sets)
- [x] Update the App component to receive and pass down props to child components
