### ISSUE TITLE
Create popup modal component for individual carousel item details

### ISSUE THREAD

**Issue by ronniefcodes** [ronniefcodes/portfolio-react#8]
## Description

When clicking individual carousel items, make a pop-up appear on where the user clicked (static, centred location on mobile/smaller devices).

## Tasks

- [ ] Create details popup component
- [ ] Attach onClick command to carousel items to trigger popup
- [ ] Add mock data for local testing
