### ISSUE TITLE
App styling

### ISSUE THREAD

**Issue by ronniefcodes** [ronniefcodes/portfolio-react#9]
## Description

This will cover all styling and layout changes required for the app.

## Tasks

- [x] Style header container (positioning, font sizes, colours and layering)
- [x] Style carousel navigation elements (colours, sizes)
- [x] Style carousel items (background image styling)
- [ ] ~Style pop up containers (requires https://github.com/ronniefcodes/portfolio-react/issues/8)~
- [x] Create improved image assets
